---
cog_bundle_version: 2

name: mist
version: 0.5.0
permissions:
- mist:view
- mist:change-state
- mist:destroy
- mist:create
- mist:manage-tags
- mist:change-acl
docker:
  image: cogcmd/mist
  tag: "0.4"
commands:
  ec2-find:
    executable: /usr/local/bin/ec2_find
    documentation: mist:ec2-find --region=<region> [--state | --tags | --ami | --return=(id,pubdns,privdns,state,keyname,ami,kernel,arch,vpc,pubip,privip,az,tags)]
    options:
      region:
        type: string
        required: true
      tags:
        type: string
        required: false
      ami:
        type: string
        required: false
      state:
        type: string
        required: false
      return:
        type: string
        required: false
    rules:
      - must have mist:view
  ec2-destroy:
    executable: /usr/local/bin/ec2_destroy
    documentation: mist:ec2-destroy --region=<region> <instance_id>...
    options:
      region:
        type: string
        required: true
    rules:
      - must have mist:destroy
  ec2-state:
    executable: /usr/local/bin/ec2_state
    documentation: mist:ec2-state --region=<region> [stop|start|reboot] <instance_id>...
    options:
      region:
        type: string
        required: true
    rules:
      - must have mist:change-state
  vpc-list:
    executable: /usr/local/bin/ec2_vpcs
    documentation: mist:vpc-list --region=<region>
    options:
      region:
        type: string
        required: true
      subnets:
        type: bool
        required: false
    rules:
      - must have mist:view
  keypairs-list:
    executable: /usr/local/bin/ec2_keypairs
    documentation: mist:keypairs-list --region=<region> <name> ...
    options:
      region:
        type: string
        required: true
    rules:
      - must have mist:view
  ec2-create:
    executable: /usr/local/bin/ec2_create
    documentation: mist:ec2-create --region=<region> --type=<type> --ami=<ami> --keypair=<pair> --az=<az> --vpc=<vpc> --tags=<tags> --user-data=<user_data>
    options:
      region:
        type: string
        required: true
      type:
        type: string
        required: true
      ami:
        type: string
        required: true
      keypair:
        type: string
        required: true
      az:
        type: string
        required: false
      vpc:
        type: string
        required: false
      tags:
        type: string
        required: false
      user-data:
        type: string
        required: false
      count:
        type: int
        required: false
    rules:
      - must have mist:create
  ec2-tags:
    executable: /usr/local/bin/ec2_tags
    documentation: mist:ec2-tags --region=<region> --tags=<tags> [add|remove|rm] ...
    options:
      region:
        type: string
        required: true
      tags:
        type: string
        required: true
    rules:
      - must have mist:manage-tags
  s3-buckets:
    executable: /usr/local/bin/s3_buckets
    documentation: s3-buckets [list|delete|create] ...
    rules:
      - must have mist:view
      - with arg[0] == 'list' must have mist:view
      - with (arg[0] == 'delete' or arg[0] == 'rm') must have mist:destroy
  s3-bucket-files:
    executable: /usr/local/bin/s3_bucket_files
    documentation: s3-bucket-files [delete|list] --force --bucket=<bucket name> --file=<search string> - List contents in a S3 bucket
    options:
      bucket:
        type: string
        required: false
      file:
        type: string
        required: false
      delete:
        type: bool
        required: false
      force:
        type: bool
        required: false
    rules:
      - must have mist:view
      - with (arg[0] == 'delete' or arg[0] == 'rm') must have mist:destroy
  s3-bucket-acl:
    executable: /usr/local/bin/s3_bucket_acl
    documentation: s3-bucket-acl [set|list] [--policy=[public-read, private, public-read-write, authenticated-read] --force] --bucket=<bucket name> --file=<filename> - Displays  or sets the ACL for a S3 bucket
    options:
      bucket:
        type: string
        required: false
      file:
        type: string
        required: false
      policy:
        type: string
        required: false
      force:
        type: bool
        required: false
    rules:
      - must have mist:view
      - with option[set-policy] == /.*/ must have mist:change-acl
