---
cog_bundle_version: 4

name: mist
version: 0.6.0
description: Basic interaction with EC2 instances and S3 buckets
long_description: |
  All commands will require AWS credentials to make requests. To correctly
  authenticate use Cog's dynamic config and set `AWS_ACCESS_KEY_ID` and
  `AWS_SECRET_ACCESS_KEY`.
author: Kevin Smith <kevin@operable.io>
homepage: https://github.com/cogcmd/mist
docker:
  image: cogcmd/mist
  tag: "0.4"
permissions:
  - mist:view
  - mist:change-state
  - mist:destroy
  - mist:create
  - mist:manage-tags
  - mist:change-acl
commands:
  ec2-find:
    executable: /usr/local/bin/ec2_find
    description: Finds an ec2 instance
    options:
      region:
        type: string
        required: true
      tags:
        type: string
        required: false
      ami:
        type: string
        required: false
      state:
        type: string
        required: false
      return:
        type: string
        required: false
        description: Valid values are id, pubdns, privdns, state, keyname, ami, kernel, arch, vpc, pubip, privip, az, tags
    rules:
      - must have mist:view
  ec2-destroy:
    executable: /usr/local/bin/ec2_destroy
    description: Destroys EC2 instances
    arguments: <instance_id> ...
    options:
      region:
        type: string
        required: true
    rules:
      - must have mist:destroy
  ec2-state:
    executable: /usr/local/bin/ec2_state
    description: Starts, stops or reboots an EC2 instance
    arguments: "[stop|start|reboot] <instance_id> ..."
    options:
      region:
        type: string
        required: true
    rules:
      - must have mist:change-state
  vpc-list:
    executable: /usr/local/bin/ec2_vpcs
    description: Lists VPCs
    options:
      region:
        type: string
        required: true
      subnets:
        type: bool
        required: false
    rules:
      - must have mist:view
  keypairs-list:
    executable: /usr/local/bin/ec2_keypairs
    description: Lists keypairs
    arguments: <name> ...
    options:
      region:
        type: string
        required: true
    rules:
      - must have mist:view
  ec2-create:
    executable: /usr/local/bin/ec2_create
    description: Creates a new EC2 instance
    options:
      region:
        type: string
        required: true
      type:
        type: string
        required: true
      ami:
        type: string
        required: true
      keypair:
        type: string
        required: true
      az:
        type: string
        required: false
      vpc:
        type: string
        required: false
      tags:
        type: string
        required: false
      user-data:
        type: string
        required: false
      count:
        type: int
        required: false
    rules:
      - must have mist:create
  ec2-tags:
    executable: /usr/local/bin/ec2_tags
    description: Manages EC2 tags
    arguments: "[add|remove|rm] ..."
    options:
      region:
        type: string
        required: true
      tags:
        type: string
        required: true
    rules:
      - must have mist:manage-tags
  s3-buckets:
    executable: /usr/local/bin/s3_buckets
    description: Manages S3 buckets
    arguments: "[list|delete|create] ..."
    rules:
      - must have mist:view
      - with arg[0] == 'list' must have mist:view
      - with (arg[0] == 'delete' or arg[0] == 'rm') must have mist:destroy
  s3-bucket-files:
    executable: /usr/local/bin/s3_bucket_files
    description: Manages files in S3 buckets
    arguments: "[delete|list]"
    options:
      bucket:
        type: string
        required: false
      file:
        type: string
        required: false
      delete:
        type: bool
        required: false
      force:
        type: bool
        required: false
    rules:
      - must have mist:view
      - with (arg[0] == 'delete' or arg[0] == 'rm') must have mist:destroy
  s3-bucket-acl:
    executable: /usr/local/bin/s3_bucket_acl
    description: Manages S3 buckets ACLs
    documentation: s3-bucket-acl [set|list]
    options:
      bucket:
        type: string
        required: false
      file:
        type: string
        required: false
      policy:
        type: string
        required: false
      force:
        type: bool
        required: false
    rules:
      - must have mist:view
      - with option[set-policy] == /.*/ must have mist:change-acl
